# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from .configuration_smolvla_ttt import SmolVLATTTConfig
from .credit_ttt_v3 import (
    CAUSAL_MEMORY_DEPLOYMENT,
    CausalMemoryDeploymentBreakdown,
    CREDIT_TTT_FORMAT,
    CREDIT_TTT_PAIR_SCHEMA,
    CREDIT_TTT_PROTOCOL,
    CREDIT_TTT_DELAY_BIN_LABELS,
    CREDIT_TTT_DELAY_EDGES,
    CREDIT_TTT_V3_FORMAT,
    CREDIT_TTT_V3_INTERVENTION,
    CREDIT_TTT_V3_INTERVENTION_SCOPE,
    CREDIT_TTT_V3_PAIR_SCHEMA,
    CREDIT_TTT_V3_PROTOCOL,
    CREDIT_TTT_V3_STATE,
    CREDIT_TTT_V3_TARGET,
    DEFAULT_CREDIT_TTT_PROTOCOL,
    FULL_HISTORY_CONTROL_ATTRIBUTION,
    QUERY_CONDITIONED_LOCAL_TTT,
    CreditPairBatch,
    CreditTTTProtocol,
    DelayBalancedPairBatch,
    InteractionFuturePair,
    InteractionFuturePairBatch,
    LocalEffectLossBreakdown,
    LocalTTTReadBeforeAfter,
    compute_symmetric_relative_utility,
    delay_balanced_pair_sampling,
    differentiable_local_update,
    functional_local_ttt_update,
    local_ttt_read_before_after,
    local_update_read_before_after,
    qh2l_loss,
    query_conditioned_effect_loss,
    query_conditioned_local_effect_loss,
    causal_memory_deployment_loss,
    causal_memory_loss,
    cmd_loss,
    query_conditioned_local_readout,
    relative_utility,
    sample_delay_balanced_pairs,
    symmetric_relative_utility,
)
from .hd_dataset import HindsightLabelDataset
from .hd_ttt import (
    HindsightAttribution,
    HindsightAttributionComputer,
    counterfactual_grounding_loss,
    compute_hindsight_attribution,
    local_kvb_loss,
)
from .history_teacher import (
    FULL_HISTORY_EVENT_SCHEMA,
    FULL_HISTORY_INTERVENTION_SCHEMA,
    FULL_HISTORY_TEACHER_FORMAT,
    HISTORY_DELETION_SCHEMA,
    HISTORY_EVENT_SCHEMA,
    HISTORY_TEACHER_FORMAT,
    CausalActionTeacher,
    CausalFullHistoryTeacher,
    CausalHistoryOutput,
    CausalHistoryState,
    CausalHistoryTeacher,
    ExplicitFullHistoryTeacher,
    FullHistoryActionOutput,
    FullHistoryActionTeacher,
    HistoryPrefixConditioner,
    PairwiseControlCredit,
    append_history_memory,
    compute_pairwise_control_credit,
    history_teacher_state_sha256,
    load_full_history_teacher_checkpoint,
    pairwise_teacher_control_credit,
    save_full_history_teacher_checkpoint,
    summarize_prefix,
    validate_full_history_teacher_provenance,
    validate_history_teacher_provenance,
)
from .modeling_smolvla_ttt import SmolVLATTTPolicy
from .processor_smolvla_ttt import make_smolvla_ttt_pre_post_processors
from .sequence import (
    HD_ACTION_SLOT_VALID_KEY,
    HD_WRITER_VALID_KEY,
    SEQUENCE_OFFSET_KEY,
    SEQUENCE_SHAPE_KEY,
    EqualLengthBatchSampler,
    TailPreservingSequenceDataset,
    batched_sequence_collate_fn,
    sequence_collate_fn,
)
from .ttt import TTTBoundedTrace, TTTFastState, TTTMLPLayer, TTTStateTransition

__all__ = [
    "SEQUENCE_SHAPE_KEY",
    "SEQUENCE_OFFSET_KEY",
    "HD_ACTION_SLOT_VALID_KEY",
    "HD_WRITER_VALID_KEY",
    "SmolVLATTTConfig",
    "SmolVLATTTPolicy",
    "CREDIT_TTT_V3_FORMAT",
    "CREDIT_TTT_V3_PROTOCOL",
    "CREDIT_TTT_V3_PAIR_SCHEMA",
    "CREDIT_TTT_V3_INTERVENTION",
    "CREDIT_TTT_V3_INTERVENTION_SCOPE",
    "CREDIT_TTT_V3_TARGET",
    "CREDIT_TTT_V3_STATE",
    "CREDIT_TTT_FORMAT",
    "CREDIT_TTT_PROTOCOL",
    "CREDIT_TTT_PAIR_SCHEMA",
    "CREDIT_TTT_DELAY_EDGES",
    "CREDIT_TTT_DELAY_BIN_LABELS",
    "FULL_HISTORY_CONTROL_ATTRIBUTION",
    "QUERY_CONDITIONED_LOCAL_TTT",
    "CAUSAL_MEMORY_DEPLOYMENT",
    "CausalMemoryDeploymentBreakdown",
    "CreditTTTProtocol",
    "DEFAULT_CREDIT_TTT_PROTOCOL",
    "InteractionFuturePair",
    "DelayBalancedPairBatch",
    "CreditPairBatch",
    "InteractionFuturePairBatch",
    "symmetric_relative_utility",
    "compute_symmetric_relative_utility",
    "relative_utility",
    "sample_delay_balanced_pairs",
    "delay_balanced_pair_sampling",
    "LocalEffectLossBreakdown",
    "query_conditioned_local_effect_loss",
    "causal_memory_deployment_loss",
    "causal_memory_loss",
    "cmd_loss",
    "query_conditioned_effect_loss",
    "qh2l_loss",
    "functional_local_ttt_update",
    "differentiable_local_update",
    "LocalTTTReadBeforeAfter",
    "local_update_read_before_after",
    "local_ttt_read_before_after",
    "query_conditioned_local_readout",
    "HindsightAttribution",
    "HindsightAttributionComputer",
    "HindsightLabelDataset",
    "TTTFastState",
    "TTTMLPLayer",
    "TTTStateTransition",
    "TTTBoundedTrace",
    "compute_hindsight_attribution",
    "counterfactual_grounding_loss",
    "local_kvb_loss",
    "HISTORY_DELETION_SCHEMA",
    "HISTORY_EVENT_SCHEMA",
    "HISTORY_TEACHER_FORMAT",
    "FULL_HISTORY_EVENT_SCHEMA",
    "FULL_HISTORY_INTERVENTION_SCHEMA",
    "FULL_HISTORY_TEACHER_FORMAT",
    "CausalActionTeacher",
    "CausalFullHistoryTeacher",
    "CausalHistoryOutput",
    "CausalHistoryState",
    "CausalHistoryTeacher",
    "ExplicitFullHistoryTeacher",
    "FullHistoryActionOutput",
    "FullHistoryActionTeacher",
    "HistoryPrefixConditioner",
    "PairwiseControlCredit",
    "append_history_memory",
    "compute_pairwise_control_credit",
    "history_teacher_state_sha256",
    "load_full_history_teacher_checkpoint",
    "pairwise_teacher_control_credit",
    "save_full_history_teacher_checkpoint",
    "summarize_prefix",
    "validate_full_history_teacher_provenance",
    "validate_history_teacher_provenance",
    "TailPreservingSequenceDataset",
    "EqualLengthBatchSampler",
    "make_smolvla_ttt_pre_post_processors",
    "batched_sequence_collate_fn",
    "sequence_collate_fn",
]
