[program:rmbench_setup_sim_env]
environment=PROC_NAME="%(program_name)s",DISABLE_PTY="true"
command=/opt/supervisor-scripts/rmbench_setup_sim_env.sh
directory=/workspace/RMBench
autostart=false
autorestart=false
exitcodes=0
startsecs=1
stopasgroup=true
killasgroup=true
stopsignal=INT
stopwaitsecs=120
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_events_enabled=true
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
