[program:rmbench_train_cover_blocks_smolvla_ttt_50x50]
environment=PROC_NAME="%(program_name)s",DISABLE_PTY="true",PYTHONUNBUFFERED="1"
command=/opt/supervisor-scripts/rmbench_train_cover_blocks_smolvla_ttt_50x50.sh
directory=/workspace
autostart=false
autorestart=false
exitcodes=0
startsecs=0
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=180
stdout_logfile=/workspace/logs/rmbench_train_cover_blocks_smolvla_ttt_50x50.log
redirect_stderr=true
stdout_logfile_maxbytes=104857600
stdout_logfile_backups=2
